### ISSUE TITLE
Provide a release jar file

### ISSUE THREAD

**Issue by KammutierSpule** [flypie/freeRouting#1]
Could you provide a release .jar file?

**Comment by flypie** [comment]
Hopefully done.

**Comment by KammutierSpule** [comment]
I cannot running the jar file:

> java freeRouting.jar
> Error: Could not find or load main class freeRouting.jar

**Comment by flypie** [comment]
You need to use "java -jar freeRouting.jar" you may also need Java SE 11 (LTS) from https://www.oracle.com/java/technologies/javase-downloads.html and run it using 

"C:\Program Files\Java\jdk-11.0.6\bin\java.exe" -jar freeRouting.jar

**Comment by KammutierSpule** [comment]
Thanks! Managed to get it work.
It looks faster than the original version!
